import math

N_ROWS = 50000  # NUMBER OF ROWS TAKEN FROM THE DATA
MAX_TEXT_LEN = 70
MAX_SEQ_LEN = 70
N_MELS = 128
SAMPLE_RATE = 16000  # NUMBER OF SAMPLES PER SECOND
HOP_LENGTH = (
    512  # THE STEP LENGTH OF THE SLIDING WINDOW, Commonly set to one-fourth of N_FFT
)
N_FFT = 2048  # NUMBER OF FFT POINTS (WINDOW SIZE) THIS CONTROLS THE RESOLUTION OF THE FREQUENCY DOMAIN ANALYSIS
CHUNK_LENGTH = 15  # 15 SECOND CHUNK
N_SAMPLES = SAMPLE_RATE * CHUNK_LENGTH
N_FRAMES = math.ceil(N_SAMPLES / HOP_LENGTH)
N_SAMPLES_PER_TOKEN = 2 * HOP_LENGTH
FRAMES_PER_SECOND = SAMPLE_RATE // HOP_LENGTH  # OR N_FRAMES // CHUNK_LENGTH
TOKENS_PER_SECOND = SAMPLE_RATE // N_SAMPLES_PER_TOKEN
NEG_INFTY = -1e9
special_tokens = ["<PAD>", "<UNK>", "<SOS>", "<EOS>"]


############################################################################################